Default: &defaults
  database: heal.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: heal_test.sqlite3
  <<: *defaults

Staging:
  database: heal_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: heal_production.sqlite3
  poolsize: 100
  <<: *defaults
