Default: &defaults
  database: eveapiproxy.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: eveapiproxy_test.sqlite3
  <<: *defaults

Staging:
  database: eveapiproxy_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: eveapiproxy_production.sqlite3
  poolsize: 100
  <<: *defaults
